### PR TITLE
Burxonov Shukurullo

### PR DESCRIPTION
**Pull request by burxonovsh**

### CODE REVIEW

**Review by bahtibek-an — CHANGES_REQUESTED** [review]
image
Your css is broken. And mostly use bootstrap classes.

**Comment by bahtibek-an** [comment]
And please when you create the branch use your fullname.

**Comment by bahtibek-an** [comment]
Send me full name to the comment.

**Comment by burxonovsh** [comment]
> Send me full name to the comment.

Burxonov Shukurullo

**Comment by burxonovsh** [comment]
> image Your css is broken. And mostly use bootstrap classes.

faqat css faylni togrlasam boldimi

**Comment by burxonovsh** [comment]
Korb bering update qilingan fayllarni

**Pull request closed without merging**
